### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [CreateChance/SimpleVideoEditor#1]
Greetings, 

I'm a graphic designer and I would be more than happy to contribute to your project by creating a logo for it, let me know if you are interested.

Best regards.

**Comment by michaelizer** [comment]
I'd like to ask some questions before starting, your answers will help me to deliver a better product.

- What's the name that should be displayed on the logo?, If there should be any.
- How would you describe this project and What is it intended to do?
- What would you like this logo to transmit?

I'll look forward to your reply, kind regards.

**Comment by CreateChance** [comment]
- What's the name that should be displayed on the logo?, If there should be any.
   SimpleVideoEditor is name of this library, so I want show this name on logo, but maybe this name is too long for show, so SVE looks good, or other good idea?
- How would you describe this project and What is it intended to do?
   Here is the reason why I design this library:
      Developing a video editor on android is too hard, less document. It needs a lot of professional knowledge.Many developers choose ffmpeg, but it has very big size and is hard to optimize. But android does not provide a good solution. I hope this library can help developers achieve development faster.
      So here is the description of this library:
            It is tiny(about 100KB size now)
            easy to use(just one line code to make edition),
            easy to extand(implementing custom effects)
- What would you like this logo to transmit?
      This library is light, easy to use(api friendly), easy to extend.

Thank you very much for you contribution.

**Comment by michaelizer** [comment]
These are some sketches

![logo_propuesta_1](https://user-images.githubusercontent.com/35619342/41254589-f383a310-6d91-11e8-997d-eca5dfe55817.jpg)
![logo_propuesta_2](https://user-images.githubusercontent.com/35619342/41254592-f46f2236-6d91-11e8-879a-d850e0f373fb.jpg)
![logo_propuesta_3](https://user-images.githubusercontent.com/35619342/41254594-f5433062-6d91-11e8-9f54-7c3a01ccf643.jpg)

Tell me what do you think of these (shape, color, etc)?

**Comment by CreateChance** [comment]
Good work! I think the last one is better, but this logo looks like a video player, not editor...... Could you please add editor information to it? And do you think add some light colors to it to  indicate lightweight design will be better? :)

**Comment by michaelizer** [comment]
These are some sketches, with one of these do you feel indentified?
![simplevideoedito_propuesta_4](https://user-images.githubusercontent.com/35619342/41385873-4a4d86fa-6f4c-11e8-8ded-fb96faa791ba.png)
![simplevideoedito_propuesta_5](https://user-images.githubusercontent.com/35619342/41385874-4aa57068-6f4c-11e8-8b19-d1a38ec9be02.png)
![simplevideoedito_propuesta_6](https://user-images.githubusercontent.com/35619342/41385876-4b205210-6f4c-11e8-850e-b0297b15b7a2.png)
![simplevideoedito_propuesta_7](https://user-images.githubusercontent.com/35619342/41385879-4c05401e-6f4c-11e8-80a6-88804e89ebbd.png)



![simplevideoedito_propuesta_3](https://user-images.githubusercontent.com/35619342/41385872-49eb49ea-6f4c-11e8-90fe-1f8bf5c89d21.png)

**Comment by CreateChance** [comment]
The first one looks good! What do you think? :)

**Comment by michaelizer** [comment]
![final_videoeditor](https://user-images.githubusercontent.com/35619342/41571825-0615e4a0-7343-11e8-9ef7-a9bc1a6ae2ed.png)
Do you like this one better? Or do you prefer the other one?

**Comment by CreateChance** [comment]
It's cool! I wonder if it would be better if we changed the color of the triangle button to gray? That way, you can highlight the editing function, not the function of the playing(In fact, we didn't provide the function of playing video).

**Comment by michaelizer** [comment]
Like this?
![ultimo](https://user-images.githubusercontent.com/35619342/41602424-c0bf2d4c-73a8-11e8-8e7e-85538079a366.png)

**Comment by michaelizer** [comment]
This is another choice, but I prefer the first one. What do you say?
![ultimo_2](https://user-images.githubusercontent.com/35619342/41629681-db1873d8-73f8-11e8-89b3-f655996ec849.png)

**Comment by CreateChance** [comment]
The first one look great! Good work! Do you think if we put the wrench at the front end will make it look better? :)

**Comment by michaelizer** [comment]
This can do the trick, what do you think?
![final_video_editor](https://user-images.githubusercontent.com/35619342/41663207-e3361c32-7470-11e8-9d99-a018ad0a8971.png)

**Comment by CreateChance** [comment]
Ok! That's it! Looks great!

**Comment by michaelizer** [comment]
@CreateChance 
Nice!
I will do some arrangements, after that I will upload the files in .SVG , .PDF, .PNG  format. Is it enough for you?

**Comment by CreateChance** [comment]
Ok, thx!

**Comment by michaelizer** [comment]
Files uploaded! ([#2](https://github.com/CreateChance/SimpleVideoEditor/pull/2)), check them. It was my pleasure, good luck with your project! 💯
