### ISSUE TITLE
Cropping

### ISSUE THREAD

**Issue by FunnyDevs** [CreateChance/SimpleVideoEditor#3]
Hi! Is possible to crop a portion on a video?

**Comment by CreateChance** [comment]
Sorry, for this time, you can not do this with this library. But you can do this by render video frame to OpenGL ES texture, and crop frame by shader. You can check my another project: https://github.com/CreateChance/AVFlow, it is still under developing, any help is welcome!

**Comment by FunnyDevs** [comment]
ok, thank you.
